### ISSUE TITLE
remove "io.d11" % "zhttp" from dependencies

### ISSUE THREAD

**Issue by domdorn** [zio/zio-metrics-connectors#2]
This project (at the moment) unnecessarily pulls in zhttp.
For using in my project that is not using zhttp but just the prometheus part I had to do 

```scala
libraryDependencies += "dev.zio" %% "zio-metrics-connectors" % "2.0.0" exclude("io.d11", "zhttp_2.13"),
```

**Comment by atooni** [comment]
Hi, zHttp is actually used by the Prometheus default layer. We can push the dependency to the prometheus module once we did the split into sub modules as suggested in #3

**Comment by domdorn** [comment]
hm.. not sure what you mean with "Prometheus default layer". nothing from zhttp is used in any of the files in https://github.com/zio/zio-metrics-connectors/tree/zio/series2.x/core/jvm/src/main/scala/zio/metrics/connectors/prometheus

Else my app would probably crash at runtime, as I've excluded the dependency and can successfully retrieve prometheus metrics using my akka-http route.

**Comment by atooni** [comment]
Might be its only in the test code, so we can Mark zhttp as a test dependency
