### ISSUE TITLE
Micrometer

### ISSUE THREAD

**Issue by Fristi** [zio/zio-metrics-connectors#20]
It seems micrometer is the SLF4j variant for metrics 

Lot's of integrations: https://micrometer.io/docs

Thoughts on integrating this? 

Gives a lot of integrations next to: statsd, prometheus and newrelic which we already have "native" implementations for.

**Comment by atooni** [comment]
Seems to be worth looking at. Ideally we would create a mapping of the metric state we have inside ZIO core to the Micrometer API. Its certainly worth to look at, perhaps in the next Hackathon. 

At the moment we are working on integrating the metrics and other information coming from the ZIO runtime into ZIO Insight to give ZIO developers a one stop shop for gaining information and Insight into a running ZIO application.

**Comment by vagroz** [comment]
What about kafka metrics? They can be collected via Micrometer meter registry. How do I publish them using PrometheusPublisher?


UPD: It would be nice to publish ZIO metrics into the Micrometer's `PrometheusMeterRegistry`, which can already collect metrics  from many libraries, including kafka metrics.

**Comment by vagroz** [comment]
Hello. Why is this issue closed?

**Comment by atooni** [comment]
AFAICS this was closed by the original requestor .

**Comment by vagroz** [comment]
Could this be re-opened? Or may I open a new one?

**Comment by atooni** [comment]
Reopened

**Comment by calvinlfer** [comment]
this is completed with @Grryum's work 😸

**Comment by Fristi** [comment]
Nice! Closing then :)
