### ISSUE TITLE
About documentation

### ISSUE THREAD

**Issue by ex0ns** [zio/zio-metrics-connectors#21]
I was looking at the doc when trying to use metrics from a ZIO projects and it seems that both https://zio.dev/zio-metrics-connectors/getting-started and the md files available on the repositories are outdated. 

Is there some work in progress regarding documentation for this project ? 
I might have the time to start working on that (at least cleaning the existing one which is misleading and would be frustrating for new users). It seems that the most accurate documentation as of now would be the content of https://www.youtube.com/watch?v=CT053oX4n5w which cover in details the usage of this library

Did I miss something ?

**Comment by atooni** [comment]
Hi there, no you did not miss anything. We are currently shifting the projects around to get a good grip on the overall metrics and monitoring strategy. If you want to help out with the documentation that would be great. Is there a timeline when you might be able to help ?

**Comment by ex0ns** [comment]
I should be able to help with that pretty soon (starting next week), my goal was to remove all the deprecated/wrong/outdated documentation  and then extract the important parts from the youtube video and provide them as written documentation for this project. I would be focusing on prometheus as a  first step as it's the only system that I know well enough to provide some valuable feedback and pointers about

**Comment by gbecan** [comment]
Hi ! I also struggled with the documentation before finding this issue. Thanks @ex0ns for the link to the video.
Do you need help for updating the documentation ?

**Comment by atooni** [comment]
That would be great :D
