### ISSUE TITLE
create submodules for newrelic, prometheus, statsd

### ISSUE THREAD

**Issue by domdorn** [zio/zio-metrics-connectors#3]
At the moment, the part for newrelic pulls in zio-json. For projects that do not need newrelic this is undesirable. It would be good if the integrations would be split into different submodules and the dependencies properly adjusted (so that e.g. zio-json is only pulled in when using the newrelic connector)

I suggest: 

- zio-metric-connectors-core
- zio-metric-connectors-newrelic
- zio-metric-connectors-statsd
- zio-metric-connectors-prometheus

as module names.

**Comment by atooni** [comment]
Hi there, that is a good idea.

**Comment by atooni** [comment]
We can remove the dependency from the prometheus connector by doing #3 and ensure we ave the zio http dependency only where it is really required.
