### ISSUE TITLE
"404 - Site Not Found" for ZIO Metrics Connectors Microsite's URL (on zio/series2.x branch)

### ISSUE THREAD

**Issue by alastor1729** [zio/zio-metrics-connectors#4]
**Reason for this Issue:**

On the **"zio/series2.x"** branch, the URL (for ZIO Metrics Connectors Microsite) is returning a 404: https://github.com/zio/zio-metrics-connectors/blob/zio/series2.x/README.md?plain=1#L34

** specifically, I see this page whenever I try to access that URL (https://zio.github.io/zio-metrics-connectors/):

![image](https://user-images.githubusercontent.com/1788960/184987673-17060a77-6d55-4776-869a-b80793af2fc0.png)

On a related-note, this is what I see for the ZIO Metrics Connectors Microsite's URL (on the **master** branch):

- master branch README.md code: https://github.com/zio/zio-metrics-connectors/blob/master/README.md?plain=1#L22
- above-URL will redirect to this web page:

![image](https://user-images.githubusercontent.com/1788960/184988273-ec52cefd-c6f1-469b-9d83-68e6f73823de.png)

If the ZIO Metrics Connectors Microsite's URL (for the **zio/series2.x** branch) is not ready yet, then please feel free to close this Issue.

Sincerely,
alastor1729

**Comment by atooni** [comment]
Hi there. At the moment we are working on the New docs, until then please refer to the content of the docs folder.

**Comment by alastor1729** [comment]
@atooni, gotcha; I will refer to this doc directory: https://github.com/zio/zio-metrics-connectors/tree/zio/series2.x/docs

Thank you!
