### ISSUE TITLE
Create an metrics connector to send metrics to OpenTelemetry

### ISSUE THREAD

**Issue by calvinlfer** [zio/zio-metrics-connectors#41]
## Context
I've seen quite a lot of clients pair up OpenTelemetry collectors in their Kubernetes clusters as a way to aggregate and send both traces and metrics to end providers like New Relic, Datadog, etc.

## Ask 
It would be great to have an opentelemetry metrics integration built directly into the project. OpenTelemetry provides a [Metrics API](https://opentelemetry.io/docs/specs/otel/metrics/api) that we can integrate with using:
* [gRPC](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto)
* REST + JSON

Additional References:
* https://opentelemetry.io/docs/specs/otel/protocol/otlp
* https://opentelemetry.io/docs/specs/otel/protocol/otlp/#json-protobuf-encoding

Note: It seems like an implementation of #20 may be able to support this as [Micrometer has support for OpenTelemetry](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/micrometer/micrometer-1.5/library/src/main/java/io/opentelemetry/instrumentation/micrometer/v1_5/OpenTelemetryMeterRegistry.java)

**Comment by omidb** [comment]
is there any guid around how to use otlp and Zio metrics?

**Comment by petoalbert** [comment]
Hi @omidb! We support OpenTelemetry through [micrometer](https://micrometer.io/) at the moment. You can read more about how to use micrometer with zio-metrics on the [zio-metrics documentation site](https://zio.dev/zio-metrics-connectors/metrics/micrometer-connector). The example in the documentation uses the prometheus-registry for micrometer, but you could plug in the opentelemetry registry according to docs here: https://micrometer.io/docs/registry/otlp
