### ISSUE TITLE
MicrometerMetricSpec gauge gets garbage collected too early

### ISSUE THREAD

**Issue by petoalbert** [zio/zio-metrics-connectors#45]
The [catch zio gauge updates](https://github.com/zio/zio-metrics-connectors/blob/zio/series2.x/micrometer/src/test/scala/zio/metrics/connectors/micrometer/MicrometerMetricsSpec.scala#L47-L53) test occasionally fails with

```
✗ NaN was not equal to 5.0
``` 

This means that the AtomicDouble representing the gauge state got [garbage collected ](https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing) somehow.

**Comment by Grryum** [comment]
@petoalbert Hi! I've fixed it, please take a look at my PR #46
