### ISSUE TITLE
Update documentation to point to new artifacts

### ISSUE THREAD

**Issue by petoalbert** [zio/zio-metrics-connectors#47]
We now publish the clients for each vendor as a separate artefacts: https://github.com/zio/zio-metrics-connectors/pull/40

We should update the [documentation](https://zio.dev/zio-metrics-connectors/getting-started) with these artifact names.

**Comment by calvinlfer** [comment]
I'll take this - thanks @petoalbert for tracking this

**Comment by calvinlfer** [comment]
I think we should merge https://github.com/zio/zio-metrics-connectors/pull/43 first and I'll take care of the rest

**Comment by petoalbert** [comment]
https://github.com/zio/zio-metrics-connectors/pull/43 is merged now. Did you have any time to take a look at this? It would be nice to update the docs along with the release of the split modules.

**Comment by calvinlfer** [comment]
Hey @petoalbert apologies for the late response, I had some time today - please see if #50 addresses most concerns

**Comment by petoalbert** [comment]
Thank you @calvinlfer for taking the time to update the docs.
