### ISSUE TITLE
Provide public api to access all metrics

### ISSUE THREAD

**Issue by oker1** [zio/zio-metrics-connectors#53]
Something similar to the functions in  `zio.metrics.connectors.internal.MetricsClient` would be useful to have access to all metrics in tests, to see what label combinations have what values currently. Having it in a -test package would be fine for me, I see it's mainly useful for connectors so having it internal by default is good IMO, application code should not read it.

**Comment by petoalbert** [comment]
Making the metric reporting easier to test would definitely be a nice feature.  👍 

> Something similar to the functions in  zio.metrics.connectors.internal.MetricsClient would be useful

Would you prefer to use something that collects [MetricEvents](https://github.com/zio/zio-metrics-connectors/blob/zio/series2.x/core/src/main/scala/zio/metrics/connectors/MetricEvent.scala) (New, Unchanged, Updated, etc) or just something that allows to directly get a snapshot of the metric registry?

**Comment by Grryum** [comment]
@oker1 maybe this feature added in ZIO 2.0.16 would suit you https://github.com/zio/zio/pull/8162

**Comment by oker1** [comment]
> @oker1 maybe this feature added in ZIO 2.0.16 would suit you [zio/zio#8162](https://github.com/zio/zio/pull/8162)

Yes this is exactly what I needed, I could adapt my test with minimal changes to it.
Thanks!
